### ISSUE TITLE
Subscribe channels

### ISSUE THREAD

**Issue by nikolay-govorov** [logux/logux-redux#6]
How to work the subscription channels? Now I call this:
```js
store.dispatch.sync(
  { type: 'logux/subscribe', channel: 'user/:id' }
)
```
I need to create a reducer 'logux/subscribe'? What should he do?

**Comment by ai** [comment]
1. `'user/:id'` → `user/12`
2. You don’t need to do anything. The server will subscribe client and will send all actions marked with `meta.channels = ['user/12']`.
