### ISSUE TITLE
Don't work with Redux DevTools Extension

### ISSUE THREAD

**Issue by Akurganow** [logux/logux-redux#9]
**How to reproduce:**
- Install [Redux DevTools for Chrome](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd)
- Open this [code example](https://codesandbox.io/s/k56njwpxpo)
- In `configure-store.js` on line 22 replace `compose` with `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__  || compose`
- Get TypeError `a.subscribe is not a function`

**Comment by ai** [comment]
Yeap, we just don't support DevTools, sorry.

Mostly because it will be useless for Logux. Time travel are now inside Logux, list of actions should use time, when action was really created.

So we're need different DevTools here.

**Comment by Akurganow** [comment]
Thanks, got it
But unfortunately logux-redux useless for me, because it is incompatible with a large part of redux ecosystem, will try to use logux-client directly and will wait logux devtools, thank you
